sudo: false
dist: trusty
language: cpp
os:
  - linux
compiler:
  - gcc
cache:
  - ccache
  - apt

addons:
   apt:
      packages: ['zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl', 'libgflags-dev']
env:
  - TEST_GROUP=1
  - TEST_GROUP=2
  - TEST_GROUP=3
  - TEST_GROUP=4
  - TEST_GROUP=5
  - TEST_GROUP=6
  # Build examples
  - JOB_NAME=examples # 5-7 minutes

install:
  - if [[ "${JOB_NAME}" == cmake* ]] && [ "${TRAVIS_OS_NAME}" == linux ]; then
      mkdir cmake-dist && curl -sfSL https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz | tar --strip-components=1 -C cmake-dist -xz && export PATH=$PWD/cmake-dist/bin:$PATH;
    fi

before_script:
  # Increase the maximum number of open file descriptors, since some tests use
  # more FDs than the default limit.
  - ulimit -n 8192

script:
  - ${CXX} --version
  - if [ `command -v ccache` ]; then ccache -C; fi
  - if [ "${TEST_GROUP}" == '1' ]; then mkdir build; cd build; cmake .. -DWITH_TESTS=ON -DROCKSDBTESTS_END=db/db_log_iter_test.cc; OPT=-DTRAVIS V=1 make -j4; ctest -j4 -V; fi
  - if [ "${TEST_GROUP}" == '2' ]; then mkdir build; cd build; cmake .. -DWITH_TESTS=ON -DROCKSDBTESTS_START=db/db_log_iter_test.cc -DROCKSDBTESTS_END=db/listener_test.cc; OPT=-DTRAVIS V=1 make -j4; ctest -j4 -V; fi
  - if [ "${TEST_GROUP}" == '3' ]; then mkdir build; cd build; cmake .. -DWITH_TESTS=ON -DROCKSDBTESTS_START=db/listener_test.cc -DROCKSDBTESTS_END=memtable/skiplist_test.cc; OPT=-DTRAVIS V=1 make -j4; ctest -j4 -V; fi
  - if [ "${TEST_GROUP}" == '4' ]; then mkdir build; cd build; cmake .. -DWITH_TESTS=ON -DROCKSDBTESTS_START=memtable/skiplist_test.cc -DROCKSDBTESTS_END=util/delete_scheduler_test.cc; OPT=-DTRAVIS V=1 make -j4; ctest -j4 -V; fi
  - if [ "${TEST_GROUP}" == '5' ]; then mkdir build; cd build; cmake .. -DWITH_TESTS=ON -DROCKSDBTESTS_START=util/delete_scheduler_test.cc -DROCKSDBTESTS_END=utilities/geodb/geodb_test.cc; OPT=-DTRAVIS V=1 make -j4; ctest -j4 -V; fi
  - if [ "${TEST_GROUP}" == '6' ]; then mkdir build; cd build; cmake .. -DWITH_TESTS=ON -DROCKSDBTESTS_START=utilities/geodb/geodb_test.cc; OPT=-DTRAVIS V=1 make -j4; ctest -j4 -V; fi
  - if [ "${JOB_NAME}" == 'examples' ]; then OPT=-DTRAVIS V=1 make -j4 static_lib; cd examples; make -j4; fi

notifications:
    email:
      - pegasus-help@xiaomi.com
    webhooks:
      - https://buildtimetrend.herokuapp.com/travis
